apiVersion: v1
kind: Service
metadata:
  name: soil
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: soil
  ports:
    - protocol: TCP
      port: 80        #  http traffic if u have certs then change to 443 LoadBalancer 
      targetPort: 80  # Must match containerPort
